/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/Book.java
 * Module: Book
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class Book {
    @NotBlank
    @Size(max = 13, min = 10, message = "ISBN should be between 10 and 13 characters")
    private String isbn;

    @NotBlank
    private String title;

    @NotBlank
    private String author;

    @NotNull
    private Integer publicationYear;

    @NotNull
    private Boolean isAvailable;

    public Book(@NotBlank @Size(max = 13, min = 10, message = "ISBN should be between 10 and 13 characters") String isbn, 
                @NotBlank String title, 
                @NotBlank String author, 
                @NotNull Integer year) {
        this.isbn = isbn;
        this.title = title;
        this.author = author;
        this.publicationYear = year;
        this.isAvailable = true;
    }

    public String getIsbn() { return isbn; }
    public String getTitle() { return title; }
    public String getAuthor() { return author; }
    public Integer getPublicationYear() { return publicationYear; }
    public Boolean isAvailable() { return isAvailable; }

    public void setAvailable(@NotNull Boolean available) {
        this.isAvailable = available;
    }

    @Override
    public String toString() {
        return "Book{" +
                "ISBN='" + isbn + '\'' +
                ", Title='" + title + '\'' +
                ", Author='" + author + '\'' +
                ", Year=" + publicationYear +
                ", Available=" + (isAvailable ? "Yes" : "No") +
                '}';
    }
}