/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/BookRepository.java
 * Module: BookRepository
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import com.converted.app.model.Book;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class BookRepository {
    private static final Logger log = LoggerFactory.getLogger(BookRepository.class);
    private final List<Book> books;

    public BookRepository() {
        this.books = new ArrayList<>();
    }
    
    public void save(Book book) {
        log.info("Saving book with ISBN: {}", book.getIsbn());
        books.add(book);
    }
    
    public Book findByIsbn(String isbn) {
        log.info("Finding book with ISBN: {}", isbn);
        for (Book book : books) {
            if (book.getIsbn().equals(isbn)) {
                return book;
            }
        }
        log.warn("No book found with ISBN: {}", isbn);
        return null;
    }
    
    public List<Book> findAll() {
        log.info("Finding all books");
        return new ArrayList<>(books);
    }
    
    public void delete(String isbn) {
        log.info("Deleting book with ISBN: {}", isbn);
        books.removeIf(book -> book.getIsbn().equals(isbn));
    }
}