/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/UserController.java
 * Module: UserController
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.controller;

import com.converted.app.service.UserService;
import com.converted.app.model.User;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/users")
public class UserController {
    private final UserService userService;

    public UserController(UserService userService) {
        this.userService = userService;
    }

    @GetMapping("/{userId}")
    public ResponseEntity<String> getUser(@PathVariable String userId) {
        return ResponseEntity.ok("Getting user: " + userId);
    }

    @PostMapping
    public ResponseEntity<String> registerUser(@RequestBody User user) {
        boolean registered = userService.registerUser(user);
        return registered ? ResponseEntity.ok("User registered") : ResponseEntity.badRequest().body("Registration failed");
    }
}